"""
Revision ID: 03b173a80418
Revises: 
Create Date: 2026-08-09 21:09:15.188141
"""

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '03b173a80418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('telefone', sa.String(length=20), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('endereco', sa.String(length=300), nullable=True),
        sa.Column('cidade', sa.String(length=100), nullable=True),
        sa.Column('estado', sa.String(length=2), nullable=True),
        sa.Column('cep', sa.String(length=9), nullable=True),
        sa.Column('data_cadastro', sa.DateTime(), nullable=True),
        sa.Column('total_compras', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'VIP', 'BLOQUEADO', name='statuscliente'), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('gastos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descricao', sa.String(length=300), nullable=False),
        sa.Column('valor', sa.Float(), nullable=False),
        sa.Column('categoria', sa.Enum('ESTOQUE', 'MARKETING', 'OPERACIONAL', 'INFRAESTRUTURA', 'OUTROS', name='categoriagasto'), nullable=False),
        sa.Column('data', sa.DateTime(), nullable=False),
        sa.Column('comprovante_url', sa.String(length=500), nullable=True),
        sa.Column('recorrente', sa.Boolean(), nullable=True),
        sa.Column('data_cadastro', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_table('mensagens_whatsapp',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('conteudo', sa.Text(), nullable=False),
        sa.Column('tipo', sa.String(length=50), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_whatsapp_id'), 'mensagens_whatsapp', ['id'], unique=False)
    op.create_table('miniaturas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('marca', sa.String(length=100), nullable=False),
        sa.Column('escala', sa.String(length=20), nullable=False),
        sa.Column('cor', sa.String(length=50), nullable=True),
        sa.Column('categoria', sa.String(length=100), nullable=True),
        sa.Column('preco_custo', sa.Float(), nullable=False),
        sa.Column('preco_venda', sa.Float(), nullable=False),
        sa.Column('quantidade', sa.Integer(), nullable=True),
        sa.Column('codigo_barras', sa.String(length=50), nullable=True),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('foto_url', sa.String(length=500), nullable=True),
        sa.Column('data_cadastro', sa.DateTime(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codigo_barras')
    )
    op.create_index(op.f('ix_miniaturas_id'), 'miniaturas', ['id'], unique=False)
    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('data_cadastro', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('pedidos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=False),
        sa.Column('data_pedido', sa.DateTime(), nullable=True),
        sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'EM_PREPARACAO', 'ENVIADO', 'ENTREGUE', 'CANCELADO', name='statuspedido'), nullable=True),
        sa.Column('valor_total', sa.Float(), nullable=True),
        sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
        sa.Column('codigo_rastreio', sa.String(length=100), nullable=True),
        sa.Column('status_entrega', sa.String(length=100), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('itens_pedido',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pedido_id', sa.Integer(), nullable=False),
        sa.Column('miniatura_id', sa.Integer(), nullable=False),
        sa.Column('quantidade', sa.Integer(), nullable=False),
        sa.Column('preco_unitario', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['miniatura_id'], ['miniaturas.id'], ),
        sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_miniaturas_id'), table_name='miniaturas')
    op.drop_table('miniaturas')
    op.drop_index(op.f('ix_mensagens_whatsapp_id'), table_name='mensagens_whatsapp')
    op.drop_table('mensagens_whatsapp')
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
